# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.main_scene = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.main_scene.setGeometry(QtCore.QRect(10, 270, 580, 270))
        self.main_scene.setTabChangesFocus(False)
        self.main_scene.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.main_scene.setReadOnly(True)
        self.main_scene.setCenterOnScroll(False)
        self.main_scene.setPlaceholderText("")
        self.main_scene.setObjectName("main_scene")
        self.specs = QtWidgets.QTableView(self.centralWidget)
        self.specs.setGeometry(QtCore.QRect(420, 10, 171, 251))
        self.specs.setObjectName("specs")
        self.inventory = QtWidgets.QTableView(self.centralWidget)
        self.inventory.setGeometry(QtCore.QRect(10, 10, 401, 171))
        self.inventory.setObjectName("inventory")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 190, 401, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.tips = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tips.sizePolicy().hasHeightForWidth())
        self.tips.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tips.setFont(font)
        self.tips.setTextFormat(QtCore.Qt.AutoText)
        self.tips.setAlignment(QtCore.Qt.AlignCenter)
        self.tips.setWordWrap(True)
        self.tips.setObjectName("tips")
        self.gridLayout.addWidget(self.tips, 0, 0, 2, 1)
        self.btn1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn1.sizePolicy().hasHeightForWidth())
        self.btn1.setSizePolicy(sizePolicy)
        self.btn1.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn1.setAutoFillBackground(False)
        self.btn1.setCheckable(False)
        self.btn1.setAutoRepeat(False)
        self.btn1.setAutoExclusive(False)
        self.btn1.setAutoDefault(False)
        self.btn1.setDefault(False)
        self.btn1.setFlat(False)
        self.btn1.setObjectName("btn1")
        self.gridLayout.addWidget(self.btn1, 0, 1, 1, 1)
        self.btn2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn2.sizePolicy().hasHeightForWidth())
        self.btn2.setSizePolicy(sizePolicy)
        self.btn2.setObjectName("btn2")
        self.gridLayout.addWidget(self.btn2, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 600, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tips.setText(_translate("MainWindow", "TextLabel"))
        self.btn1.setText(_translate("MainWindow", "START"))
        self.btn2.setText(_translate("MainWindow", "INFO"))

